// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPUInfo struct {
	CPU int `json:"cpu"`
}

type HostInfo struct {
	Uptime               int    `json:"uptime"`
	HostName             string `json:"hostName"`
	HostID               string `json:"hostID"`
	Os                   string `json:"os"`
	Platform             string `json:"platform"`
	PlatformFamily       string `json:"platformFamily"`
	PlatformVersion      string `json:"platformVersion"`
	KernelVersion        string `json:"kernelVersion"`
	KernelArch           string `json:"kernelArch"`
	VirtualizationSystem string `json:"virtualizationSystem"`
	VirtualizationRole   string `json:"virtualizationRole"`
}

type ProcessItem struct {
	Name string `json:"name"`
	Pid  int    `json:"pid"`
	Vms  int    `json:"vms"`
	Hwm  int    `json:"hwm"`
}
